// <auto-generated />
using System;
using AlchemistApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlchemistApi.Migrations
{
    [DbContext(typeof(AlchemistGameContext))]
    [Migration("20260930210518_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlchemistApi.Models.CauldronUpgrade", b =>
                {
                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CraftTimeModifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3, 2)")
                        .HasDefaultValue(1.0m);

                    b.Property<int>("MaxIngredients")
                        .HasColumnType("integer");

                    b.Property<int>("UpgradeCostGold")
                        .HasColumnType("integer");

                    b.HasKey("Level")
                        .HasName("PK__Cauldron__AAF8996301680C8E");

                    b.ToTable("CauldronUpgrades");
                });

            modelBuilder.Entity("AlchemistApi.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BasePrice")
                        .HasColumnType("integer");

                    b.Property<string>("IconPath")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("RarityId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK__Items__3214EC07AD579FCA");

                    b.HasIndex("RarityId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("AlchemistApi.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CauldronLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("Energy")
                        .HasColumnType("integer");

                    b.Property<int?>("Experience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("Gold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("LastEnergyUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MaxEnergy")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SkillPoints")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK__Players__3214EC07AE347488");

                    b.HasIndex("CauldronLevel");

                    b.HasIndex(new[] { "Nickname" }, "UQ__Players__CC6CD17ECC37648B")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("AlchemistApi.Models.PlayerBrew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReadyAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ResultItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ResultItemId");

                    b.ToTable("PlayerBrews", (string)null);
                });

            modelBuilder.Entity("AlchemistApi.Models.PlayerInventory", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "ItemId")
                        .HasName("PK__PlayerIn__ED699CF02A26041C");

                    b.HasIndex("ItemId");

                    b.ToTable("PlayerInventory", (string)null);
                });

            modelBuilder.Entity("AlchemistApi.Models.PlayerQuest", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("PlayerId", "QuestId")
                        .HasName("PK__PlayerQu__E1286D6A692AB7DF");

                    b.HasIndex("QuestId");

                    b.ToTable("PlayerQuests");
                });

            modelBuilder.Entity("AlchemistApi.Models.PlayerRecipe", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PlayerId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("PlayerRecipes", (string)null);
                });

            modelBuilder.Entity("AlchemistApi.Models.PlayerSkill", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("PlayerSkills", (string)null);
                });

            modelBuilder.Entity("AlchemistApi.Models.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsRepeatable")
                        .HasColumnType("boolean");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("integer");

                    b.Property<int>("RewardGold")
                        .HasColumnType("integer");

                    b.Property<int>("RewardXp")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id")
                        .HasName("PK__Quests__3214EC07D2246A3B");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("AlchemistApi.Models.QuestRequirement", b =>
                {
                    b.Property<int>("QuestId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityNeeded")
                        .HasColumnType("integer");

                    b.HasKey("QuestId", "ItemId")
                        .HasName("PK__QuestReq__114672134BE28B4F");

                    b.HasIndex("ItemId");

                    b.ToTable("QuestRequirements");
                });

            modelBuilder.Entity("AlchemistApi.Models.Rarity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("PK__Rarities__3214EC07362BCA1C");

                    b.ToTable("Rarities");
                });

            modelBuilder.Entity("AlchemistApi.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrewTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("RequiredSkillId")
                        .HasColumnType("integer");

                    b.Property<int?>("RequiredXp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("ResultItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK__Recipes__3214EC07E19765D7");

                    b.HasIndex("ResultItemId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("AlchemistApi.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientItemId")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityNeeded")
                        .HasColumnType("integer");

                    b.HasKey("RecipeId", "IngredientItemId")
                        .HasName("PK__RecipeIn__8A399C04FEE93838");

                    b.HasIndex("IngredientItemId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("AlchemistApi.Models.ShopAssortment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("PurchasePrice")
                        .HasColumnType("integer");

                    b.Property<int?>("RequiredPlayerLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id")
                        .HasName("PK__ShopAsso__3214EC076C0E96EF");

                    b.HasIndex("ItemId");

                    b.ToTable("ShopAssortment", (string)null);
                });

            modelBuilder.Entity("AlchemistApi.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EffectType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("EffectValue")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("IconPath")
                        .HasColumnType("text");

                    b.Property<int>("MaxRank")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PrerequisiteSkillId")
                        .HasColumnType("integer");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Skills", (string)null);
                });

            modelBuilder.Entity("AlchemistApi.Models.Item", b =>
                {
                    b.HasOne("AlchemistApi.Models.Rarity", "Rarity")
                        .WithMany("Items")
                        .HasForeignKey("RarityId")
                        .HasConstraintName("FK__Items__RarityId__5070F446");

                    b.Navigation("Rarity");
                });

            modelBuilder.Entity("AlchemistApi.Models.Player", b =>
                {
                    b.HasOne("AlchemistApi.Models.CauldronUpgrade", "CauldronLevelNavigation")
                        .WithMany("Players")
                        .HasForeignKey("CauldronLevel")
                        .HasConstraintName("FK__Players__Cauldro__571DF1D5");

                    b.Navigation("CauldronLevelNavigation");
                });

            modelBuilder.Entity("AlchemistApi.Models.PlayerBrew", b =>
                {
                    b.HasOne("AlchemistApi.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlchemistApi.Models.Item", "ResultItem")
                        .WithMany()
                        .HasForeignKey("ResultItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("ResultItem");
                });

            modelBuilder.Entity("AlchemistApi.Models.PlayerInventory", b =>
                {
                    b.HasOne("AlchemistApi.Models.Item", "Item")
                        .WithMany("PlayerInventories")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK__PlayerInv__ItemI__5AEE82B9");

                    b.HasOne("AlchemistApi.Models.Player", "Player")
                        .WithMany("PlayerInventories")
                        .HasForeignKey("PlayerId")
                        .IsRequired()
                        .HasConstraintName("FK__PlayerInv__Playe__59FA5E80");

                    b.Navigation("Item");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("AlchemistApi.Models.PlayerQuest", b =>
                {
                    b.HasOne("AlchemistApi.Models.Player", "Player")
                        .WithMany("PlayerQuests")
                        .HasForeignKey("PlayerId")
                        .IsRequired()
                        .HasConstraintName("FK__PlayerQue__Playe__71D1E811");

                    b.HasOne("AlchemistApi.Models.Quest", "Quest")
                        .WithMany("PlayerQuests")
                        .HasForeignKey("QuestId")
                        .IsRequired()
                        .HasConstraintName("FK__PlayerQue__Quest__72C60C4A");

                    b.Navigation("Player");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("AlchemistApi.Models.PlayerRecipe", b =>
                {
                    b.HasOne("AlchemistApi.Models.Player", "Player")
                        .WithMany("PlayerRecipes")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlchemistApi.Models.Recipe", "Recipe")
                        .WithMany("PlayerRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("AlchemistApi.Models.PlayerSkill", b =>
                {
                    b.HasOne("AlchemistApi.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlchemistApi.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("AlchemistApi.Models.QuestRequirement", b =>
                {
                    b.HasOne("AlchemistApi.Models.Item", "Item")
                        .WithMany("QuestRequirements")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK__QuestRequ__ItemI__6E01572D");

                    b.HasOne("AlchemistApi.Models.Quest", "Quest")
                        .WithMany("QuestRequirements")
                        .HasForeignKey("QuestId")
                        .IsRequired()
                        .HasConstraintName("FK__QuestRequ__Quest__6D0D32F4");

                    b.Navigation("Item");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("AlchemistApi.Models.Recipe", b =>
                {
                    b.HasOne("AlchemistApi.Models.Item", "ResultItem")
                        .WithMany("Recipes")
                        .HasForeignKey("ResultItemId")
                        .HasConstraintName("FK__Recipes__ResultI__5EBF139D");

                    b.Navigation("ResultItem");
                });

            modelBuilder.Entity("AlchemistApi.Models.RecipeIngredient", b =>
                {
                    b.HasOne("AlchemistApi.Models.Item", "IngredientItem")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientItemId")
                        .IsRequired()
                        .HasConstraintName("FK__RecipeIng__Ingre__6383C8BA");

                    b.HasOne("AlchemistApi.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .IsRequired()
                        .HasConstraintName("FK__RecipeIng__Recip__628FA481");

                    b.Navigation("IngredientItem");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("AlchemistApi.Models.ShopAssortment", b =>
                {
                    b.HasOne("AlchemistApi.Models.Item", "Item")
                        .WithMany("ShopAssortments")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("FK__ShopAssor__ItemI__6754599E");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("AlchemistApi.Models.CauldronUpgrade", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("AlchemistApi.Models.Item", b =>
                {
                    b.Navigation("PlayerInventories");

                    b.Navigation("QuestRequirements");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("Recipes");

                    b.Navigation("ShopAssortments");
                });

            modelBuilder.Entity("AlchemistApi.Models.Player", b =>
                {
                    b.Navigation("PlayerInventories");

                    b.Navigation("PlayerQuests");

                    b.Navigation("PlayerRecipes");
                });

            modelBuilder.Entity("AlchemistApi.Models.Quest", b =>
                {
                    b.Navigation("PlayerQuests");

                    b.Navigation("QuestRequirements");
                });

            modelBuilder.Entity("AlchemistApi.Models.Rarity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AlchemistApi.Models.Recipe", b =>
                {
                    b.Navigation("PlayerRecipes");

                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
